### ISSUE TITLE
Feature Request: Support HIFI

### ISSUE THREAD

**Issue by PHoBwz** [valknight/tidal-desktop#2]
Currently as the app isn't seen as a chrome browser it doesn't support HIFI audio channels. Although only chrome is supported I use firefox and I still get HIFI support.

**Comment by amblabs** [comment]
I second this request!  I have a Tidal HIFI subscription and it would be really nice to be able to enjoy it on Linux.  I don't use WIndows or MacOS, currently  the only way I could get Tidal HIFI is by running the web player in the Chrome or Firefox browser, or on my iPhone with the Tidal app (which also supports "Master").  Running the web player in the browser is cumbersome and seem to chew up all my available memory...

How hard is it to enable HIFI support?

**Comment by amblabs** [comment]
In the "Settings > Streaming" tab, under "Streaming Audio Quality,  the "HiFi" button is greyed out.  It says "Requires browser with Widevine support".  I see the libwidevinecdm.so and libwidevinecdmadapter.so libraries in /usr/lib6/chromium directory, so I added symlinks to them in the tidal-linux-x64 directory.  This doesn't have an effect.  So it appears that the tidal for Linux wrapper itself needs to make use of the Widevine libraries.

**Comment by amblabs** [comment]
I got HIFI to work! This is with Michsior14's fork of tidal-desktop (see the "DRM error" issue thread) compiled on my openSUSE Leap 15.0 system, which also has Google chrome installed in /opt/google/chrome.  All I needed to do was add a symlink of the Widevine shared library /opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so into the tidal-linux-x64 directory and restart tidal.  Now HIFI mode is no longer greyed out and I can switch to it.

**Comment by amblabs** [comment]
Update: I also tried symlinking the Widevine library that comes with the chromium browser /usr/lib64/chromium/libwidevinecdm.so into the tidal-linux-x64 directory, and that works too.

**Comment by dspacejs** [comment]
Strongly agree, the only reason I use Tidal instead of Spotify is because of HiFi/master audio quality. The web player supports HiFi so I'm not sure why it doesn't work for this if it's just embedding the web app in Electron?

**Comment by amblabs** [comment]
@dspacejs See the two posts above yours, HIFI works if you use Michsior14's fork of tidal-desktop and compile it yourself, then symlink the libwidevinecdm.so lbrary into the tidal directory.

**Comment by dspacejs** [comment]
@amblabs oops I didn't read that lol. Great, going to give it a shot. Any chance this fork will be merged into the main repo?

**Comment by dspacejs** [comment]
@amblabs I symlinked `libwidevinecdm.so` into `tidal-linux-x64`, but this didn't work. Am I missing something?

**Comment by amblabs** [comment]
The original author valknight no longer has a tidal account so he is no longer maintaining or doing new development on it.  So consider this branch dead.

As for libwidevinecdm.so, which one did you symlibk to? And did you build tidal-desktop from Michsior14's branch?

**Comment by PHoBwz** [comment]
Here is the better branch to use:
https://github.com/Michsior14/tidal-desktop
